config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root "users#index"

  resources :receipts
  resources :notes
  resources :debts
  resources :users
  resources :mailshots
  resources :news

end

app/models/debt.rb
class Debt < ActiveRecord::Base
	belongs_to :user
end

app/models/mailshot.rb
class Mailshot < ActiveRecord::Base
  belongs_to :user
end

app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :user
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :student, class_name: 'User'
	belongs_to :teacher, class_name: 'User'

	def self.search_note_by_subject(search)
	  where("subject LIKE ?", "%#{search}%")
	end

end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
	belongs_to :user
	mount_uploader :receiptFile, ReceiptFileUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  after_create :assign_role
  serialize :debts
  has_many :receipts
  has_many :notes
  has_many :debts
  has_many :mailshots
  has_many :news

  def assign_role
  	if self.username == "admin"
  		self.add_role(:admin) if self.roles.blank?
  	elsif self.role == "student"
      self.add_role(:student) if self.roles.blank?
    elsif self.role == "teacher"
      self.add_role(:teacher) if self.roles.blank?
    end

  end

  # Prepares an attribute that is not represented by a column in
  # the database table, but can still be used in the forms
  attr_accessor :add_debt

  # Performs a callback on save to check if any debts should be added
  # and if there is, it appends to the existing array instead of replacing

  before_save do
    if !self.debts.nil?
      if @add_debt.present?
        self.debts << @add_debt
      end
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable

  def self.search_students(search)
    where("names LIKE ? OR last_names LIKE ? OR identification LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%").where("role = ?", "student" )
  end

  def self.search_teachers(search)
    where("names LIKE ? OR last_names LIKE ? OR identification LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%").where("role = ?", "teacher" )
  end
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController

	def create
		debt = Debt.new(debt_params)
		debt.user_id = params[:user_id]
		debt.save

		redirect_to :back
	end

	def destroy
		debt = Debt.find(params[:debt_id])
		debt.destroy
		redirect_to :back
	end

	private
		def debt_params
			params.require(:debt).permit(:date, :description)
		end
end

app/controllers/mailshot_controller.rb
class MailshotController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/mailshots_controller.rb
class MailshotsController < ApplicationController
  def new
  	@mailshot = Mailshot.new
  end

  def create
  	mailshot = Mailshot.new(mailshot_params)
  	mailshot.user_id = params[:user_id]
  	mailshot.save
  	redirect_to root_path
  end

  def show
  	@mailshot = Mailshot.find(params[:id])
  end

  def destroy
    mailshot = Mailshot.find(params[:id])
    mailshot.destroy
    redirect_to root_path
  end

  private
  	def mailshot_params
  		params.require(:mailshot).permit(:body, :grade, :title)
  	end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def new
    @news = News.new
  end

  def create
    news = News.new(news_params)
    news.user_id = params[:user_id]
    news.save
    redirect_to root_path
  end

  def show
    @news = News.find(params[:id])
  end

  def destroy
    news = News.find(params[:id])
    news.destroy
    redirect_to root_path
  end

  private
    def news_params
      params.require(:news).permit(:body, :title)
    end

  def index
    @news = News.all
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	def create
		note = Note.new(note_params)
		note.student_id = params[:student_id]
		note.teacher_id = params[:teacher_id]
		note.save

		redirect_to :back
	end


	private
		def note_params
			params.require(:note).permit(:description, :grade, :subject, :student_id, :teacher_id)
		end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController

	def create
		receipt = Receipt.new(receipt_params)
		receipt.user_id = params[:user_id]
		receipt.save

		redirect_to :back
	end

	private
		def receipt_params
			params.require(:receipt).permit(:date, :receiptFile)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	layout "landing", :only => :index

	def index
		if params[:search]
			@students = User.search_students(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
			@teachers = User.search_teachers(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
		else
			@students = User.with_role(:student).paginate(:page => params[:page], :per_page => 15)
			@teachers = User.with_role(:teacher).paginate(:page => params[:page], :per_page => 15)
		end
		@mailshots = Mailshot.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
	end

	def show
		@notes = Note.all.paginate(:page => params[:page], :per_page => 15)
		@students = User.with_role(:student)
		@user = User.find(params[:id])
		@mailshots = Mailshot.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)



		if params[:search]
			@students = User.search_students(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
		end

		if params[:subject_search]
			@notes = Note.search_note_by_subject(params[:subject_search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
		end

		if params[:reset_subjects_search]
			@notes = Note.all
		end

		#receipts creation code
		@receipt = Receipt.new

		#note creation code
		@note = Note.new

		#debt creation code
		@debt = Debt.new
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
		if user.update!(user_update_params)
			redirect_to user
		else
			redirect_to root_path
		end
	end

	private
		def user_update_params
			params.require(:user).permit(:username, :names, :last_names, :guardian, :phone, :identification, :role, :password, :password_confirmation)
		end

		def user_params
			if @user.debts.nil?
				params.require(:user).permit(:debts)
			else
				params.require(:user).permit(:add_debt)
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/helpers/mailshot_helper.rb
module MailshotHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/receipt_helper.rb
module ReceiptHelper
end

app/views/layouts/_nav_bar.html.erb
<% if current_user %>
  <% if current_page?(root_path) and !current_user.has_role? :admin %>
    <!-- Aquí va el navbar para cuando los estudiantes o profesores esten logueados y visitan el landing. pero al admin no le salga nada -->

    <!-- render "layouts/nav_bar_landing"  -->
  <% else %>
    <%= render "layouts/nav_bar_panel" %>
  <% end %>
<% end %>

<% if current_page?(root_path) and !current_user %>
  <!-- Aquí va el navbar del landing page cuando no hay nadie logueado-->
  <!--  render "layouts/nav_bar_landing"  -->
<% end %>




app/views/layouts/_nav_bar_landing.html.erb

<!-- Navigation -->
<nav class="navbar navbar-default custom navbar-fixed-top navbar-shrink">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        	<center>
        		<ul class="nav custom navbar-nav navbar-right">
        		    <li class="hidden active">
        		        <a href="#page-top"></a>
        		    </li>
        		    <li class="">
        		        <a class="page-scroll info-opt" href="">Información</a>
        		    </li>
        		    <li class="">
        		        <a class="page-scroll eng-opt" href="">Inglés</a>
        		    </li>
        		    <li class="">
        		        <a class="page-scroll cont-opt" href="">Contacto</a>
        		    </li>

        		    <% if current_user %>
        		    	<li>
        		    		<%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete  %>
        		    	</li>
        		    <% else %>
        		    	<li>
        		    		<%= link_to "Iniciar Sesión", new_user_session_path %>
        		    	</li>
        		    <% end %>
        		</ul>
        	</center>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_bar_panel.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <%= link_to "Frida Kahlo", root_path, class: "navbar-brand" %>
    </div>

    <% if current_user %>
      <% if current_user.has_role? :admin %>
        <%= form_tag(root_path, :method => "get", id: "navBarSearchForm", class: "navbar-form navbar-left", role: "search") do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Buscar usuarios por nombre, apellido o identificación", class: "form-control" %>
          </div>
          <%= submit_tag "Buscar", class: "btn btn-default" %>
        <% end %>


        <ul class=" navbar-nav admin">
          <li>
            <%= link_to new_mailshot_path, class: "no-space" do %>
              <button type="button" class="btn btn-primary navbar-btn">Crear Circular</button>
            <% end %>
          </li>

          <li>
            <%= link_to new_news_path, class: "no-space" do %>
              <button type="button" class="btn btn-primary navbar-btn">Crear Noticia</button>
            <% end %>
          </li>

          <li>
            <%= link_to new_user_registration_path, class: "no-space" do %>
              <button type="button" class="btn btn-primary navbar-btn">Agregar Usuario</button>
            <% end %>
          </li>

        </ul>
      <% end %>
    <% end %>

    <ul class=" navbar-nav navbar-right">
      <% if !current_user%>
        <li>
          <%= link_to new_user_session_path, class: "no-space" do %>
            <button type="button" class="btn btn-default navbar-btn">Iniciar Sesión</button>
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to destroy_user_session_path, class: "no-space", method: :delete do %>
            <button type="button" class="btn btn-default navbar-btn">Cerrar Sesión</button>
          <% end %>
        </li>
      <% end %>
    <li><p class="invisible">aaaaaa   </p></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScolarManagementSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
  <link href="https://fonts.googleapis.com/css?family=Arsenal" rel="stylesheet">
</head>
<body>

	<%= render "layouts/nav_bar" %>
	<%= yield %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>
	<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScolarManagementSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
  <link href="https://fonts.googleapis.com/css?family=Arsenal" rel="stylesheet">
</head>
<body>
  <% if current_user%>
    <% if !current_user.has_role? :admin %>
      <h1>Funciono</h1>
    <% else %>
      <%= render "layouts/nav_bar" %>
    <% end %>
  <% else %>
    <h1>Funciono</h1>
  <% end %>
  <%= yield %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
</body>
</html>